/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.DisciplineBUS;
import BUS.DiscliproroleBUS;
import DTO.Discipline;
import DTO.Discliprorole;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class DisciplinePanel extends javax.swing.JPanel {

    DisciplineBUS disBUS = new DisciplineBUS();
    DiscliproroleBUS disroleBUS = new DiscliproroleBUS();
    public DisciplinePanel() {
        initComponents();
        
        loadDataTable();
        loadDataRoleTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void loadDataTable() {
        DefaultTableModel model = (DefaultTableModel) DisList.getModel();
        model.setRowCount(0); // xóa table 
        for (Discipline dis : disBUS.getAllDiscipline()) {
            Object dataRow[] = new Object[3];
            dataRow[0] = dis.getDis_ID();
            dataRow[1] = dis.getDis_Content();
            dataRow[2] = dis.getDis_Score();
            model.addRow(dataRow);
        }
    }
    public void loadDataRoleTable() {
        DefaultTableModel model = (DefaultTableModel) disRoleList.getModel();
        model.setRowCount(0); // xóa table 
        for (Discliprorole disrole : disroleBUS.getAllDiscliprorole()) {
            Object dataRow[] = new Object[2];
            dataRow[0] = disrole.getRoleID();
            dataRow[1] = disrole.getRoleContent();
            model.addRow(dataRow);
        }
    }
    public Discipline getdisModel() {
        Discipline dis = new Discipline();
        String Dis_ID = txtRole.getText();
        dis.setDis_ID(Dis_ID);
        String Dis_Content = txtContent.getText();
        dis.setDis_Content(Dis_Content);
        String Dis_Score = txtScore.getText();
        dis.setDis_Score(Float.parseFloat(Dis_Score));
        return dis;
    }
    public void setdisModel(Discipline dis) {
        txtRole.setText(dis.getDis_ID());
        txtContent.setText(dis.getDis_Content());
        txtScore.setText(String.valueOf(dis.getDis_Score()));
    }
    public Discliprorole getdisroleModel() {
        Discliprorole disrole = new Discliprorole();
        String RoleID = txtdisRole.getText();
        disrole.setRoleID(RoleID);
        String DisContent = txtdisContent.getText();
        disrole.setRoleContent(DisContent);
        return disrole;
    }
    public void setdisroleModel(Discliprorole disrole) {
        txtdisRole.setText(disrole.getRoleID());
        txtdisContent.setText(disrole.getRoleContent());
    }
    public boolean validatedisForm() {
        if(txtRole.getText().isEmpty()) {
            return false;
        }
        return true;
    }
    
    public boolean validatedisroleForm() {
        if(txtdisRole.getText().isEmpty()) {
            return false;
        }
        return true;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisDialog = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtRole = new javax.swing.JTextField();
        txtContent = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtScore = new javax.swing.JTextField();
        addDisBtn = new javax.swing.JButton();
        btnEsc = new javax.swing.JButton();
        editDisBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        RoledisDialog = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtdisRole = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdisContent = new javax.swing.JTextField();
        adddisRoleBtn = new javax.swing.JButton();
        btnEsc1 = new javax.swing.JButton();
        editdisRoleBtn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Btnshowdis = new javax.swing.JButton();
        btneditdis = new javax.swing.JButton();
        btndeletedis = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisList = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnshowdisrole = new javax.swing.JButton();
        btneditdisrole = new javax.swing.JButton();
        btndeletedisrole = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        disRoleList = new javax.swing.JTable();

        DisDialog.setMinimumSize(new java.awt.Dimension(385, 408));
        DisDialog.setModal(true);
        DisDialog.setUndecorated(true);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Quản lý tài khoản"));

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel2.setText("Mục");

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel4.setText("Điểm");

        addDisBtn.setBackground(new java.awt.Color(204, 0, 204));
        addDisBtn.setForeground(new java.awt.Color(255, 255, 255));
        addDisBtn.setText("Thêm");
        addDisBtn.setPreferredSize(new java.awt.Dimension(100, 35));
        addDisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDisBtnActionPerformed(evt);
            }
        });

        btnEsc.setBackground(new java.awt.Color(255, 0, 0));
        btnEsc.setForeground(new java.awt.Color(255, 255, 255));
        btnEsc.setText("X");
        btnEsc.setPreferredSize(new java.awt.Dimension(100, 35));
        btnEsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscActionPerformed(evt);
            }
        });

        editDisBtn.setBackground(new java.awt.Color(255, 153, 51));
        editDisBtn.setForeground(new java.awt.Color(255, 255, 255));
        editDisBtn.setText("Sửa");
        editDisBtn.setPreferredSize(new java.awt.Dimension(100, 35));
        editDisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDisBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel6.setText("Nội Dung");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtContent, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2)
                        .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(addDisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editDisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEsc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(btnEsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DisDialogLayout = new javax.swing.GroupLayout(DisDialog.getContentPane());
        DisDialog.getContentPane().setLayout(DisDialogLayout);
        DisDialogLayout.setHorizontalGroup(
            DisDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
            .addGroup(DisDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DisDialogLayout.createSequentialGroup()
                    .addContainerGap(15, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        DisDialogLayout.setVerticalGroup(
            DisDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
            .addGroup(DisDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DisDialogLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        RoledisDialog.setMinimumSize(new java.awt.Dimension(385, 408));
        RoledisDialog.setModal(true);
        RoledisDialog.setUndecorated(true);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Quản lý tài khoản"));

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel5.setText("Mục");

        jLabel7.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel7.setText("Nội Dung");

        adddisRoleBtn.setBackground(new java.awt.Color(204, 0, 204));
        adddisRoleBtn.setForeground(new java.awt.Color(255, 255, 255));
        adddisRoleBtn.setText("Thêm");
        adddisRoleBtn.setPreferredSize(new java.awt.Dimension(100, 35));
        adddisRoleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddisRoleBtnActionPerformed(evt);
            }
        });

        btnEsc1.setBackground(new java.awt.Color(255, 0, 0));
        btnEsc1.setForeground(new java.awt.Color(255, 255, 255));
        btnEsc1.setText("X");
        btnEsc1.setPreferredSize(new java.awt.Dimension(100, 35));
        btnEsc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsc1ActionPerformed(evt);
            }
        });

        editdisRoleBtn.setBackground(new java.awt.Color(255, 153, 51));
        editdisRoleBtn.setForeground(new java.awt.Color(255, 255, 255));
        editdisRoleBtn.setText("Sửa");
        editdisRoleBtn.setPreferredSize(new java.awt.Dimension(100, 35));
        editdisRoleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editdisRoleBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEsc1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdisContent, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(txtdisRole, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(adddisRoleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editdisRoleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(btnEsc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdisRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdisContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editdisRoleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adddisRoleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RoledisDialogLayout = new javax.swing.GroupLayout(RoledisDialog.getContentPane());
        RoledisDialog.getContentPane().setLayout(RoledisDialogLayout);
        RoledisDialogLayout.setHorizontalGroup(
            RoledisDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
            .addGroup(RoledisDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RoledisDialogLayout.createSequentialGroup()
                    .addContainerGap(15, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        RoledisDialogLayout.setVerticalGroup(
            RoledisDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
            .addGroup(RoledisDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RoledisDialogLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        setMinimumSize(new java.awt.Dimension(1050, 600));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Thao tác"));

        Btnshowdis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Add.png"))); // NOI18N
        Btnshowdis.setMaximumSize(new java.awt.Dimension(60, 60));
        Btnshowdis.setMinimumSize(new java.awt.Dimension(60, 60));
        Btnshowdis.setPreferredSize(new java.awt.Dimension(60, 60));
        Btnshowdis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnshowdisActionPerformed(evt);
            }
        });

        btneditdis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Edit.png"))); // NOI18N
        btneditdis.setMaximumSize(new java.awt.Dimension(60, 60));
        btneditdis.setMinimumSize(new java.awt.Dimension(60, 60));
        btneditdis.setPreferredSize(new java.awt.Dimension(60, 60));
        btneditdis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditdisActionPerformed(evt);
            }
        });

        btndeletedis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Remove.png"))); // NOI18N
        btndeletedis.setMaximumSize(new java.awt.Dimension(60, 60));
        btndeletedis.setMinimumSize(new java.awt.Dimension(60, 60));
        btndeletedis.setPreferredSize(new java.awt.Dimension(60, 60));
        btndeletedis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletedisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btnshowdis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btneditdis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btndeletedis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btndeletedis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneditdis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btnshowdis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách"));

        DisList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mục", "Nội dung", "Điểm"
            }
        ));
        DisList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DisListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DisList);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Kỷ luật", jPanel1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Thao tác"));

        btnshowdisrole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Add.png"))); // NOI18N
        btnshowdisrole.setMaximumSize(new java.awt.Dimension(60, 60));
        btnshowdisrole.setMinimumSize(new java.awt.Dimension(60, 60));
        btnshowdisrole.setPreferredSize(new java.awt.Dimension(60, 60));
        btnshowdisrole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowdisroleActionPerformed(evt);
            }
        });

        btneditdisrole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Edit.png"))); // NOI18N
        btneditdisrole.setMaximumSize(new java.awt.Dimension(60, 60));
        btneditdisrole.setMinimumSize(new java.awt.Dimension(60, 60));
        btneditdisrole.setPreferredSize(new java.awt.Dimension(60, 60));
        btneditdisrole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditdisroleActionPerformed(evt);
            }
        });

        btndeletedisrole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Remove.png"))); // NOI18N
        btndeletedisrole.setMaximumSize(new java.awt.Dimension(60, 60));
        btndeletedisrole.setMinimumSize(new java.awt.Dimension(60, 60));
        btndeletedisrole.setPreferredSize(new java.awt.Dimension(60, 60));
        btndeletedisrole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletedisroleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnshowdisrole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btneditdisrole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btndeletedisrole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btndeletedisrole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneditdisrole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnshowdisrole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách"));

        disRoleList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mục", "Nội dung"
            }
        ));
        disRoleList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disRoleListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(disRoleList);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 800, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Mục", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btneditdisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditdisActionPerformed
        // TODO add your handling code here:
        DisDialog.setLocationRelativeTo(null);
        addDisBtn.setVisible(false);
        editDisBtn.setVisible(true);
        DisDialog.setVisible(true);   
    }//GEN-LAST:event_btneditdisActionPerformed

    private void btneditdisroleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditdisroleActionPerformed
        RoledisDialog.setLocationRelativeTo(null);
        adddisRoleBtn.setVisible(false);
        editdisRoleBtn.setVisible(true);
        RoledisDialog.setVisible(true);             // TODO add your handling code here:
    }//GEN-LAST:event_btneditdisroleActionPerformed

    private void DisListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisListMouseClicked
        int row = DisList.rowAtPoint(evt.getPoint());
        String Dis_ID = DisList.getValueAt(row, 0).toString();
        Discipline dis = disBUS.getDisciplineByID(Dis_ID);
        setdisModel(dis);
    }//GEN-LAST:event_DisListMouseClicked

    private void addDisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDisBtnActionPerformed
        Discipline dis = getdisModel();
        if (disBUS.addDiscipline(dis)) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            loadDataTable();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
        }
        loadDataTable();
    }//GEN-LAST:event_addDisBtnActionPerformed

    private void editDisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDisBtnActionPerformed
        Discipline dis = getdisModel();
        if (disBUS.editDiscipline(dis)) {
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            loadDataTable();
        } else {
            JOptionPane.showMessageDialog(this, "Sửa thất bại");
        }
        loadDataTable();
    }//GEN-LAST:event_editDisBtnActionPerformed

    private void btnEscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscActionPerformed
        // TODO add your handling code here:
        DisDialog.setVisible(false);
    }//GEN-LAST:event_btnEscActionPerformed

    private void adddisRoleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddisRoleBtnActionPerformed
        Discliprorole disrole = getdisroleModel();
        if (disroleBUS.addDiscliprorole(disrole)) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            loadDataTable();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
        }
        loadDataRoleTable();
    }//GEN-LAST:event_adddisRoleBtnActionPerformed

    private void btnEsc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsc1ActionPerformed
      RoledisDialog.setVisible(false); 
    }//GEN-LAST:event_btnEsc1ActionPerformed

    private void editdisRoleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editdisRoleBtnActionPerformed
        Discliprorole disrole = getdisroleModel();
        if (disroleBUS.editDiscliprorole(disrole)) {
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            loadDataTable();
        } else {
            JOptionPane.showMessageDialog(this, "Sửa thất bại");
        }
        loadDataRoleTable();
    }//GEN-LAST:event_editdisRoleBtnActionPerformed

    private void btnshowdisroleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowdisroleActionPerformed
        RoledisDialog.setLocationRelativeTo(null);
        adddisRoleBtn.setVisible(true);
        editdisRoleBtn.setVisible(false);
        RoledisDialog.setVisible(true);        // TODO add your handling code 
    }//GEN-LAST:event_btnshowdisroleActionPerformed

    private void BtnshowdisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnshowdisActionPerformed
        DisDialog.setLocationRelativeTo(null);
        addDisBtn.setVisible(true);
        editDisBtn.setVisible(false);
        DisDialog.setVisible(true);   
    }//GEN-LAST:event_BtnshowdisActionPerformed

    private void btndeletedisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletedisActionPerformed
        if(validatedisForm()) {
            Discipline dis = getdisModel();
            if(disBUS.deleteDiscipline(dis.getDis_ID())) {
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                loadDataTable();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn tài khoản cần xóa");      
        }
        loadDataTable();
    }//GEN-LAST:event_btndeletedisActionPerformed

    private void disRoleListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disRoleListMouseClicked
        int row = disRoleList.rowAtPoint(evt.getPoint());
        String roleID = disRoleList.getValueAt(row, 0).toString();
        Discliprorole disrole = disroleBUS.getDiscliproroleByID(roleID);
        setdisroleModel(disrole);
    }//GEN-LAST:event_disRoleListMouseClicked

    private void btndeletedisroleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletedisroleActionPerformed
        if(validatedisroleForm()) {
            Discliprorole disrole = getdisroleModel();
            if(disroleBUS.deleteDiscliprorole(disrole.getRoleID())) {
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                loadDataTable();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn tài khoản cần xóa");      
        }
        loadDataRoleTable();
    }//GEN-LAST:event_btndeletedisroleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnshowdis;
    private javax.swing.JDialog DisDialog;
    private javax.swing.JTable DisList;
    private javax.swing.JDialog RoledisDialog;
    private javax.swing.JButton addDisBtn;
    private javax.swing.JButton adddisRoleBtn;
    private javax.swing.JButton btnEsc;
    private javax.swing.JButton btnEsc1;
    private javax.swing.JButton btndeletedis;
    private javax.swing.JButton btndeletedisrole;
    private javax.swing.JButton btneditdis;
    private javax.swing.JButton btneditdisrole;
    private javax.swing.JButton btnshowdisrole;
    private javax.swing.JTable disRoleList;
    private javax.swing.JButton editDisBtn;
    private javax.swing.JButton editdisRoleBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtContent;
    private javax.swing.JTextField txtRole;
    private javax.swing.JTextField txtScore;
    private javax.swing.JTextField txtdisContent;
    private javax.swing.JTextField txtdisRole;
    // End of variables declaration//GEN-END:variables
}
