/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.ClassBUS;
import BUS.GradeBUS;
import BUS.SchoolYearBUS;
import BUS.TeacherBUS;
import DTO.Grade;
import DTO.Class;
import DTO.SchoolYear;
import DTO.Teacher;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author M S I
 */
public class ClassGradePanel extends javax.swing.JPanel {

    /**
     * Creates new form TeacherPanel
     */
    GradeBUS gradeBUS = new GradeBUS();
    ClassBUS classBUS = new ClassBUS();
    SchoolYearBUS schoolYearBUS = new SchoolYearBUS();
    TeacherBUS teacherBUS = new TeacherBUS();
    private String[] factor = new String[4];

    public ClassGradePanel() {
        initComponents();
        loadDataTableGrade();
        loadDataTableClass();
        loadcombobox();
    }

    private void loadDataTableClass() {
        DefaultTableModel model = (DefaultTableModel) classList.getModel();
        model.setRowCount(0); // xóa table
        for (Class class1 : classBUS.getAllClass()) {
            Object dataRow[] = new Object[6];
            dataRow[0] = class1.getClassID();
            dataRow[1] = class1.getClassName();
            dataRow[2] = class1.getGradeID();
            dataRow[3] = class1.getQuantity();
            dataRow[4] = class1.getShoolyear();
            dataRow[5] = class1.getTeacherID();
            model.addRow(dataRow);
        }

    }

    private void loadDataTableGrade() {
        DefaultTableModel gmodel = (DefaultTableModel) gradeList.getModel();
        gmodel.setRowCount(0); // xóa table 
        for (Grade grade : gradeBUS.getAllGrades()) {
            Object gdataRow[] = new Object[2];
            gdataRow[0] = grade.getGradeID();
            gdataRow[1] = grade.getGradeName();
            gmodel.addRow(gdataRow);
            System.out.println(grade.toString());
        }
    }

    private void loadDataClassFactor(String[] factor) {
        DefaultTableModel model = (DefaultTableModel) classList.getModel();
        model.setRowCount(0); // xóa table
        for (Class class1 : classBUS.getClassFactor(factor)) {
            Object dataRow[] = new Object[6];
            dataRow[0] = class1.getClassID();
            dataRow[1] = class1.getClassName();
            dataRow[2] = class1.getGradeID();
            dataRow[3] = class1.getQuantity();
            dataRow[4] = class1.getShoolyear();
            dataRow[5] = class1.getTeacherID();
            model.addRow(dataRow);
            System.out.println(class1.toString());
        }
    }

    private void loadcombobox() {
        DefaultComboBoxModel comboSchoolYear = new DefaultComboBoxModel();
        comboSchoolYear.addElement("");
        for (SchoolYear schoolYear : schoolYearBUS.getAllSchoolYear()) {
            comboSchoolYear.addElement(schoolYear.getSchoolYearID());
        }
        SchoolYearBox.setModel(comboSchoolYear);
        SchoolYearBox.setModel(comboSchoolYear);
        orderByBox.addItem("Mã Lớp");
        orderByBox.addItem("Tên lớp");
        orderByBox.addItem("KHối");
        orderByBox.addItem("SL Học sinh");
        orderByBox.addItem("Giáo viên");
        RiseBtn.setSelected(true);
        orderByBox.setSelectedIndex(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradeDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtGradeID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtGradeName = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        btnAddGrade = new javax.swing.JButton();
        btnEditGrade = new javax.swing.JButton();
        btnEsc1 = new javax.swing.JButton();
        classDialog = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtClassID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtClassTeacher = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtClassName = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        btnAddClass = new javax.swing.JButton();
        btnEditClass = new javax.swing.JButton();
        btnEsc = new javax.swing.JButton();
        txtClassSchoolYear = new javax.swing.JTextField();
        txtClassQuantity = new javax.swing.JTextField();
        txtClassGrade = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        classPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        showClassDialog = new javax.swing.JButton();
        btnShowEditClassDialog = new javax.swing.JButton();
        btnDeleteClass = new javax.swing.JButton();
        btnExportExcelClass = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        classList = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        RGrade10Btn = new javax.swing.JRadioButton();
        RGrade11Btn = new javax.swing.JRadioButton();
        RGrade12Btn = new javax.swing.JRadioButton();
        SchoolYearBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        orderByBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        RiseBtn = new javax.swing.JRadioButton();
        LowBtn = new javax.swing.JRadioButton();
        gradePanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        showGradeDialog = new javax.swing.JButton();
        showEditGradeDialog = new javax.swing.JButton();
        deleteGrade = new javax.swing.JButton();
        btnExportExcelGrade = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradeList = new javax.swing.JTable();

        gradeDialog.setMinimumSize(new java.awt.Dimension(267, 232));
        gradeDialog.setModal(true);
        gradeDialog.setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin khối"));

        jLabel9.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mã Khối");

        txtGradeID.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tên Khối");

        txtGradeName.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N

        jPanel12.setForeground(new java.awt.Color(255, 255, 255));

        btnAddGrade.setBackground(new java.awt.Color(209, 15, 209));
        btnAddGrade.setForeground(new java.awt.Color(255, 255, 255));
        btnAddGrade.setText("Thêm");
        btnAddGrade.setPreferredSize(new java.awt.Dimension(100, 35));
        btnAddGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGradeActionPerformed(evt);
            }
        });
        jPanel12.add(btnAddGrade);

        btnEditGrade.setBackground(new java.awt.Color(255, 153, 51));
        btnEditGrade.setForeground(new java.awt.Color(255, 255, 255));
        btnEditGrade.setText("Sửa");
        btnEditGrade.setPreferredSize(new java.awt.Dimension(100, 35));
        btnEditGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditGradeActionPerformed(evt);
            }
        });
        jPanel12.add(btnEditGrade);

        btnEsc1.setBackground(new java.awt.Color(255, 0, 0));
        btnEsc1.setForeground(new java.awt.Color(255, 255, 255));
        btnEsc1.setText("Thoát");
        btnEsc1.setPreferredSize(new java.awt.Dimension(100, 35));
        btnEsc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsc1ActionPerformed(evt);
            }
        });
        jPanel12.add(btnEsc1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(txtGradeID, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtGradeName))
                .addContainerGap(21, Short.MAX_VALUE))
            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGradeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGradeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout gradeDialogLayout = new javax.swing.GroupLayout(gradeDialog.getContentPane());
        gradeDialog.getContentPane().setLayout(gradeDialogLayout);
        gradeDialogLayout.setHorizontalGroup(
            gradeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        gradeDialogLayout.setVerticalGroup(
            gradeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        classDialog.setMinimumSize(new java.awt.Dimension(263, 471));
        classDialog.setModal(true);
        classDialog.setUndecorated(true);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin lớp học", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Variable", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mã Lớp");

        txtClassID.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sĩ số");

        txtClassTeacher.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GVCN");

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Năm học");

        jLabel6.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Khối");

        jLabel7.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tên lớp");

        txtClassName.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N

        jPanel11.setForeground(new java.awt.Color(255, 255, 255));

        btnAddClass.setBackground(new java.awt.Color(209, 15, 209));
        btnAddClass.setForeground(new java.awt.Color(255, 255, 255));
        btnAddClass.setText("Thêm");
        btnAddClass.setPreferredSize(new java.awt.Dimension(100, 35));
        btnAddClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClassActionPerformed(evt);
            }
        });
        jPanel11.add(btnAddClass);

        btnEditClass.setBackground(new java.awt.Color(255, 153, 51));
        btnEditClass.setForeground(new java.awt.Color(255, 255, 255));
        btnEditClass.setText("Sửa");
        btnEditClass.setPreferredSize(new java.awt.Dimension(100, 35));
        btnEditClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditClassActionPerformed(evt);
            }
        });
        jPanel11.add(btnEditClass);

        btnEsc.setBackground(new java.awt.Color(255, 0, 0));
        btnEsc.setForeground(new java.awt.Color(255, 255, 255));
        btnEsc.setText("Thoát");
        btnEsc.setPreferredSize(new java.awt.Dimension(100, 35));
        btnEsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscActionPerformed(evt);
            }
        });
        jPanel11.add(btnEsc);

        txtClassSchoolYear.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N

        txtClassQuantity.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N

        txtClassGrade.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClassName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtClassID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(txtClassTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(txtClassSchoolYear, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtClassQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtClassGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClassID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClassGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClassQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClassTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClassSchoolYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout classDialogLayout = new javax.swing.GroupLayout(classDialog.getContentPane());
        classDialog.getContentPane().setLayout(classDialogLayout);
        classDialogLayout.setHorizontalGroup(
            classDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        classDialogLayout.setVerticalGroup(
            classDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classDialogLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        setPreferredSize(new java.awt.Dimension(1050, 600));

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1050, 600));

        classPanel.setPreferredSize(new java.awt.Dimension(1050, 600));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Thao tác"));

        showClassDialog.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        showClassDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Add.png"))); // NOI18N
        showClassDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showClassDialogActionPerformed(evt);
            }
        });

        btnShowEditClassDialog.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        btnShowEditClassDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Edit.png"))); // NOI18N
        btnShowEditClassDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowEditClassDialogActionPerformed(evt);
            }
        });

        btnDeleteClass.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        btnDeleteClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Remove.png"))); // NOI18N
        btnDeleteClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteClassActionPerformed(evt);
            }
        });

        btnExportExcelClass.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        btnExportExcelClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/XLS.png"))); // NOI18N
        btnExportExcelClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportExcelClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showClassDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnShowEditClassDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteClass, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExportExcelClass, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnShowEditClassDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(showClassDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnDeleteClass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnExportExcelClass, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách lớp học"));

        classList.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        classList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã lớp", "Tên lớp", "Khối", "Sĩ số", "Năm học", "GVCN"
            }
        ));
        classList.setRowHeight(30);
        classList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(classList);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Lọc "));

        buttonGroup1.add(RGrade10Btn);
        RGrade10Btn.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        RGrade10Btn.setText("Khối 10");
        RGrade10Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RGrade10BtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(RGrade11Btn);
        RGrade11Btn.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        RGrade11Btn.setText("Khối 11");
        RGrade11Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RGrade11BtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(RGrade12Btn);
        RGrade12Btn.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        RGrade12Btn.setText("Khối 12");
        RGrade12Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RGrade12BtnActionPerformed(evt);
            }
        });

        SchoolYearBox.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        SchoolYearBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SchoolYearBoxActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        jLabel11.setText("Năm học");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RGrade10Btn)
                .addGap(18, 18, 18)
                .addComponent(RGrade11Btn)
                .addGap(18, 18, 18)
                .addComponent(RGrade12Btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SchoolYearBox, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RGrade10Btn)
                    .addComponent(RGrade11Btn)
                    .addComponent(RGrade12Btn)
                    .addComponent(jLabel11)
                    .addComponent(SchoolYearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Sắp xếp"));

        orderByBox.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        orderByBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderByBoxActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        jLabel12.setText("Sắp xếp theo");

        buttonGroup2.add(RiseBtn);
        RiseBtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        RiseBtn.setText("Tăng dần");
        RiseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiseBtnActionPerformed(evt);
            }
        });

        buttonGroup2.add(LowBtn);
        LowBtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        LowBtn.setText("Giảm dần");
        LowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LowBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderByBox, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RiseBtn)
                .addGap(18, 18, 18)
                .addComponent(LowBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderByBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(RiseBtn)
                    .addComponent(LowBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout classPanelLayout = new javax.swing.GroupLayout(classPanel);
        classPanel.setLayout(classPanelLayout);
        classPanelLayout.setHorizontalGroup(
            classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(classPanelLayout.createSequentialGroup()
                        .addGroup(classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        classPanelLayout.setVerticalGroup(
            classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lớp học", classPanel);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Thao tác"));

        showGradeDialog.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        showGradeDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Add.png"))); // NOI18N
        showGradeDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showGradeDialogActionPerformed(evt);
            }
        });

        showEditGradeDialog.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        showEditGradeDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Edit.png"))); // NOI18N
        showEditGradeDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showEditGradeDialogActionPerformed(evt);
            }
        });

        deleteGrade.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        deleteGrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Remove.png"))); // NOI18N
        deleteGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteGradeActionPerformed(evt);
            }
        });

        btnExportExcelGrade.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        btnExportExcelGrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/XLS.png"))); // NOI18N
        btnExportExcelGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportExcelGradeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showGradeDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(showEditGradeDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExportExcelGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showEditGradeDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showGradeDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExportExcelGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách khối lớp"));

        gradeList.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        gradeList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã khối lớp", "Tên khối lớp"
            }
        ));
        gradeList.setRowHeight(30);
        gradeList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradeListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gradeList);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout gradePanelLayout = new javax.swing.GroupLayout(gradePanel);
        gradePanel.setLayout(gradePanelLayout);
        gradePanelLayout.setHorizontalGroup(
            gradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(gradePanelLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        gradePanelLayout.setVerticalGroup(
            gradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Khối Lớp", gradePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean validateFormClass() {
        if (txtClassID.getText().isEmpty() || txtClassName.getText().isEmpty() || txtClassID.getText().isEmpty()
                || txtClassTeacher.getText().isEmpty() || txtClassSchoolYear.getText().isEmpty()
                || txtClassTeacher.getText().isEmpty()) {
            return false;
        }
        return true;
    }

    public void setModelClass(Class class1) {
        txtClassID.setText(class1.getClassID());
        txtClassName.setText(class1.getClassName());
        txtClassGrade.setText(class1.getGradeID());
        txtClassQuantity.setText(class1.getQuantity() + "");
        txtClassSchoolYear.setText(class1.getShoolyear());
        txtClassTeacher.setText(class1.getTeacherID());
    }

    public Class getModelClass() {
        Class class1 = new Class();
        class1.setClassID(txtClassID.getText());
        class1.setClassName(txtClassName.getText());
        class1.setGradeID(txtClassGrade.getText());
        if(Integer.valueOf(txtClassQuantity.getText())>40){
            txtClassQuantity.setText("40");
        }
        else
        class1.setQuantity(Integer.parseInt(txtClassQuantity.getText()));
        class1.setShoolyear(txtClassSchoolYear.getText());
        class1.setTeacherID(txtClassTeacher.getText());
        return class1;
    }

    public void resetClass() {
        txtClassID.setText("");
        txtClassName.setText("");
        txtClassGrade.setText("");
        txtClassQuantity.setText("");
        txtClassSchoolYear.setText("");
        txtClassTeacher.setText("");
    }


    private void btnAddClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClassActionPerformed
        if (validateFormClass()) {
            Class class1 = getModelClass();
            if (classBUS.addClass(class1)) {
                JOptionPane.showMessageDialog(this, "Thêm lớp thành công");
                loadDataTableClass();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");

        }

    }//GEN-LAST:event_btnAddClassActionPerformed

    private void btnEditClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditClassActionPerformed
        if (validateFormClass()) {
            Class class1 = getModelClass();
            if (classBUS.editClass(class1)) {
                JOptionPane.showMessageDialog(this, "Sửa lớp thành công");
                loadDataTableClass();
            } else {
                JOptionPane.showMessageDialog(this, "Sửa thất bại");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");

        }
    }//GEN-LAST:event_btnEditClassActionPerformed

    private void btnEscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscActionPerformed
        // TODO add your handling code here:
        classDialog.setVisible(false);
    }//GEN-LAST:event_btnEscActionPerformed

    private void showClassDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showClassDialogActionPerformed
        // TODO add your handling code here:
        classDialog.setLocationRelativeTo(null);
        resetClass();
        btnAddClass.setVisible(true);
        btnEditClass.setVisible(false);
        classDialog.setVisible(true);
    }//GEN-LAST:event_showClassDialogActionPerformed

    public boolean validateFormGrade() {
        if (txtGradeID.getText().isEmpty() || txtGradeName.getText().isEmpty()) {
            return false;
        }
        return true;
    }


    private void btnAddGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGradeActionPerformed
        // TODO add your handling code here:
        if (validateFormGrade()) {
            Grade grade = getModelGrade();
            if (gradeBUS.addGrade(grade)) {
                JOptionPane.showMessageDialog(this, "Thêm khối thành công");
                loadDataTableGrade();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");

        }
    }//GEN-LAST:event_btnAddGradeActionPerformed

    private void btnEditGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditGradeActionPerformed
        // TODO add your handling code here:
        Grade grade = getModelGrade();
        if (gradeBUS.editGrade(grade)) {
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            loadDataTableGrade();
        } else {
            JOptionPane.showMessageDialog(this, "Sửa thất bại");
        }
    }//GEN-LAST:event_btnEditGradeActionPerformed

    private void btnEsc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsc1ActionPerformed
        // TODO add your handling code here:
        resetGrade();
        gradeDialog.setVisible(false);
    }//GEN-LAST:event_btnEsc1ActionPerformed

    public void setModelGrade(Grade grade) {
        txtGradeID.setText(grade.getGradeID());
        txtGradeName.setText(grade.getGradeName());
    }

    public Grade getModelGrade() {
        Grade grade = new Grade();
        grade.setGradeID(txtGradeID.getText());
        grade.setGradeName(txtGradeName.getText());
        return grade;
    }

    public void resetGrade() {
        txtGradeID.setText("");
        txtGradeName.setText("");
    }

    private void showGradeDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showGradeDialogActionPerformed
        // TODO add your handling code here:
        gradeDialog.setLocationRelativeTo(null);
        resetGrade();
        btnEditGrade.setVisible(false);
        btnAddGrade.setVisible(true);
        gradeDialog.setVisible(true);
    }//GEN-LAST:event_showGradeDialogActionPerformed

    private void showEditGradeDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showEditGradeDialogActionPerformed
        // TODO add your handling code here:
        if (validateFormGrade()) {
            gradeDialog.setLocationRelativeTo(null);
            btnAddGrade.setVisible(false);
            btnEditGrade.setVisible(true);
            gradeDialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khối cần sửa");
        }
    }//GEN-LAST:event_showEditGradeDialogActionPerformed

    private void gradeListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradeListMouseClicked
        // TODO add your handling code here:
        int row = gradeList.rowAtPoint(evt.getPoint());
        String GradeID = gradeList.getValueAt(row, 0).toString();
        Grade grade = gradeBUS.getGradeByID(GradeID);
        setModelGrade(grade);
    }//GEN-LAST:event_gradeListMouseClicked

    private void deleteGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteGradeActionPerformed
        // TODO add your handling code here:
        if (validateFormGrade()) {
            Grade grade = getModelGrade();
            if (gradeBUS.deleteGrade(grade)) {
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                loadDataTableGrade();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bai");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khối cần xóa");
        }
    }//GEN-LAST:event_deleteGradeActionPerformed

    private void RGrade10BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RGrade10BtnActionPerformed
        factor[0] = SchoolYearBox.getSelectedItem().toString();
        factor[1] = "KHOI10%";
        factor[2] = orderByBox.getSelectedItem().toString();
        if (RGrade10Btn.isSelected()) {
            loadDataClassFactor(factor);
            RGrade12Btn.setSelected(false);
            RGrade11Btn.setSelected(false);
        } else {
            factor[1] = " ";
            loadDataTableClass();
        }
    }//GEN-LAST:event_RGrade10BtnActionPerformed

    private void classListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classListMouseClicked
        // TODO add your handling code here:
        int row = classList.rowAtPoint(evt.getPoint());
        String ClassID = classList.getValueAt(row, 0).toString();
        Class class1 = classBUS.getClassByID(ClassID);
        setModelClass(class1);
    }//GEN-LAST:event_classListMouseClicked

    private void btnDeleteClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteClassActionPerformed
        // TODO add your handling code here:
        if (validateFormClass()) {
            Class class1 = getModelClass();
            if (classBUS.deleteClass(class1)) {
                JOptionPane.showMessageDialog(this, "Xóa thành công lớp học");
                loadDataTableClass();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn lớp học muốn xóa");

        }
    }//GEN-LAST:event_btnDeleteClassActionPerformed

    private void btnShowEditClassDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowEditClassDialogActionPerformed
        if (validateFormClass()) {
            classDialog.setLocationRelativeTo(null);
            btnAddClass.setVisible(false);
            btnEditClass.setVisible(true);
            classDialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn lớp học muốn sửa");
        }

    }//GEN-LAST:event_btnShowEditClassDialogActionPerformed

    private void LowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LowBtnActionPerformed
// TODO add your handling code here:
        if (RGrade10Btn.isSelected()) {
            factor[1] = "KHOI10";
        } else if (RGrade11Btn.isSelected()) {
            factor[1] = "KHOI11";
        } else if (RGrade12Btn.isSelected()) {
            factor[1] = "KHOI12";
        } else {
            factor[1] = " ";
        }
        factor[0] = SchoolYearBox.getSelectedItem().toString();
        factor[2] = orderByBox.getSelectedItem().toString();
        factor[3] = "Low";
        if (LowBtn.isSelected()) {
            RiseBtn.setSelected(false);
            loadDataClassFactor(factor);
        } else {
            RiseBtn.setSelected(true);
            loadDataClassFactor(factor);
        }
    }//GEN-LAST:event_LowBtnActionPerformed

    private void RiseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiseBtnActionPerformed
// TODO add your handling code here:
        if (RGrade10Btn.isSelected()) {
            factor[1] = "KHOI10";
        } else if (RGrade11Btn.isSelected()) {
            factor[1] = "KHOI11";
        } else if (RGrade12Btn.isSelected()) {
            factor[1] = "KHOI12";
        } else {
            factor[1] = " ";
        }
        factor[0] = SchoolYearBox.getSelectedItem().toString();
        factor[2] = orderByBox.getSelectedItem().toString();
        factor[3] = "Rise";
        if (RiseBtn.isSelected()) {
            LowBtn.setSelected(false);
            loadDataClassFactor(factor);
        } else {
            LowBtn.setSelected(true);
            loadDataClassFactor(factor);
        }
     }//GEN-LAST:event_RiseBtnActionPerformed

    private void SchoolYearBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SchoolYearBoxActionPerformed
// TODO add your handling code here:
        factor[0] = SchoolYearBox.getSelectedItem().toString();
        if (factor[0] == "") {
            loadDataTableClass();
        } else {
            if (RGrade10Btn.isSelected()) {
                factor[1] = "KHOI10";
            } else if (RGrade11Btn.isSelected()) {
                factor[1] = "KHOI11";
            } else if (RGrade12Btn.isSelected()) {
                factor[1] = "KHOI12";
            } else {
                factor[1] = " ";
            }
            factor[2] = orderByBox.getSelectedItem().toString();
            if (RiseBtn.isSelected()) {
                factor[3] = "Rise";
            } else {
                factor[3] = "Low";
            }
            SchoolYearBox.setSelectedItem(ABORT);
            loadDataClassFactor(factor);
        }


    }//GEN-LAST:event_SchoolYearBoxActionPerformed

    private void orderByBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderByBoxActionPerformed
// TODO add your handling code here:
        factor[0] = SchoolYearBox.getSelectedItem().toString();
        if (RGrade10Btn.isSelected()) {
            factor[1] = "KHOI10";
        } else if (RGrade11Btn.isSelected()) {
            factor[1] = "KHOI11";
        } else if (RGrade12Btn.isSelected()) {
            factor[1] = "KHOI12";
        } else {
            factor[1] = " ";
        }
        factor[2] = orderByBox.getSelectedItem().toString();
        if (RiseBtn.isSelected()) {
            factor[3] = "Rise";
        } else {
            factor[3] = "Low";
        }
        orderByBox.setSelectedItem(ABORT);
        loadDataClassFactor(factor);
    }//GEN-LAST:event_orderByBoxActionPerformed

    private void RGrade11BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RGrade11BtnActionPerformed
        factor[0] = SchoolYearBox.getSelectedItem().toString();
        factor[1] = "KHOI11%";
        factor[2] = orderByBox.getSelectedItem().toString();
        if (RGrade11Btn.isSelected()) {
            loadDataClassFactor(factor);
            RGrade10Btn.setSelected(false);
            RGrade12Btn.setSelected(false);
        } else {
            factor[1] = " ";
            loadDataClassFactor(factor);
        }
    }//GEN-LAST:event_RGrade11BtnActionPerformed

    private void RGrade12BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RGrade12BtnActionPerformed
        factor[0] = SchoolYearBox.getSelectedItem().toString();
        if (RGrade10Btn.isSelected()) {
            factor[1] = "KHOI10";
        } else if (RGrade11Btn.isSelected()) {
            factor[1] = "KHOI11";
        } else if (RGrade12Btn.isSelected()) {
            factor[1] = "KHOI12";
        } else {
            factor[1] = " ";
        }
        factor[2] = orderByBox.getSelectedItem().toString();
        if (RiseBtn.isSelected()) {
            factor[3] = "Rise";
        } else {
            factor[3] = "Low";
        }
        SchoolYearBox.setSelectedItem(ABORT);
        loadDataClassFactor(factor);

    }//GEN-LAST:event_RGrade12BtnActionPerformed

    private void btnExportExcelClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportExcelClassActionPerformed
// TODO add your handling code here:
        try {
            JFileChooser choose = new JFileChooser();
            choose.showOpenDialog(JOptionPane.getRootFrame());
            File save = choose.getSelectedFile();
            if (save != null) {
                save = new File(save.toString() + ".xlsx");
                Workbook wb = new XSSFWorkbook();
                Sheet sheet = (Sheet) wb.createSheet("Tổng kết điểm kỳ học");
                Row rowcol = sheet.createRow(0);
                for (int i = 0; i < classList.getColumnCount(); i++) {
                    Cell cell = rowcol.createCell(i);
                    cell.setCellValue(classList.getColumnName(i));
                }
                for (int i = 0; i < classList.getRowCount(); i++) {
                    Row row = sheet.createRow(i + 1);
                    for (int j = 0; j < classList.getColumnCount(); j++) {
                        Cell cell = row.createCell(j);
                        if (classList.getValueAt(i, j) != null) {
                            cell.setCellValue(classList.getValueAt(i, j).toString());
                        }
                    }
                }
                FileOutputStream out = new FileOutputStream(new File(save.toString()));
                wb.write(out);
                wb.close();
                out.close();
                openFile(save.toString());
            } else {
                JOptionPane.showMessageDialog(null, "Error al genera");
            }
        } catch (Exception u) {
            u.printStackTrace();
        }
    }//GEN-LAST:event_btnExportExcelClassActionPerformed

    private void btnExportExcelGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportExcelGradeActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser choose = new JFileChooser();
            choose.showOpenDialog(JOptionPane.getRootFrame());
            File save = choose.getSelectedFile();
            if (save != null) {
                save = new File(save.toString() + ".xlsx");
                Workbook wb = new XSSFWorkbook();
                Sheet sheet = (Sheet) wb.createSheet("Tổng kết điểm kỳ học");
                Row rowcol = sheet.createRow(0);
                for (int i = 0; i < gradeList.getColumnCount(); i++) {
                    Cell cell = rowcol.createCell(i);
                    cell.setCellValue(gradeList.getColumnName(i));
                }
                for (int i = 0; i < gradeList.getRowCount(); i++) {
                    Row row = sheet.createRow(i + 1);
                    for (int j = 0; j < gradeList.getColumnCount(); j++) {
                        Cell cell = row.createCell(j);
                        if (gradeList.getValueAt(i, j) != null) {
                            cell.setCellValue(gradeList.getValueAt(i, j).toString());
                        }
                    }
                }
                FileOutputStream out = new FileOutputStream(new File(save.toString()));
                wb.write(out);
                wb.close();
                out.close();
                openFile(save.toString());
            } else {
                JOptionPane.showMessageDialog(null, "Error al genera");
            }
        } catch (Exception u) {
            u.printStackTrace();
        }
    }//GEN-LAST:event_btnExportExcelGradeActionPerformed
    public void openFile(String file) {
        try {
            File path = new File(file);
            Desktop.getDesktop().open(path);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton LowBtn;
    private javax.swing.JRadioButton RGrade10Btn;
    private javax.swing.JRadioButton RGrade11Btn;
    private javax.swing.JRadioButton RGrade12Btn;
    private javax.swing.JRadioButton RiseBtn;
    private javax.swing.JComboBox<String> SchoolYearBox;
    private javax.swing.JButton btnAddClass;
    private javax.swing.JButton btnAddGrade;
    private javax.swing.JButton btnDeleteClass;
    private javax.swing.JButton btnEditClass;
    private javax.swing.JButton btnEditGrade;
    private javax.swing.JButton btnEsc;
    private javax.swing.JButton btnEsc1;
    private javax.swing.JButton btnExportExcelClass;
    private javax.swing.JButton btnExportExcelGrade;
    private javax.swing.JButton btnShowEditClassDialog;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JDialog classDialog;
    private javax.swing.JTable classList;
    private javax.swing.JPanel classPanel;
    private javax.swing.JButton deleteGrade;
    private javax.swing.JDialog gradeDialog;
    private javax.swing.JTable gradeList;
    private javax.swing.JPanel gradePanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> orderByBox;
    private javax.swing.JButton showClassDialog;
    private javax.swing.JButton showEditGradeDialog;
    private javax.swing.JButton showGradeDialog;
    private javax.swing.JTextField txtClassGrade;
    private javax.swing.JTextField txtClassID;
    private javax.swing.JTextField txtClassName;
    private javax.swing.JTextField txtClassQuantity;
    private javax.swing.JTextField txtClassSchoolYear;
    private javax.swing.JTextField txtClassTeacher;
    private javax.swing.JTextField txtGradeID;
    private javax.swing.JTextField txtGradeName;
    // End of variables declaration//GEN-END:variables
}
