/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.FunctionBUS;
import BUS.PermissionDetailBUS;
import BUS.RoleBUS;
import DTO.Function;
import DTO.PermissionDetail;
import DTO.Role;
import java.awt.Desktop;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author M S I
 */
public class PermissionPanel extends javax.swing.JPanel {

    /**
     * Creates new form PermissionPanel
     */
    RoleBUS roleBUS = new RoleBUS();
    FunctionBUS functionBUS = new FunctionBUS();
    PermissionDetailBUS permissionDetailBUS = new PermissionDetailBUS();

    public PermissionPanel() {
        initComponents();
        loadComboboxRole();
        loadComboboxFunction();
        loadDataRole();
        loadDataFunction();
        loadDataPermissionDetail();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InputRoleDialog = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtRoleName = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnAddRole = new javax.swing.JButton();
        btnEditRole = new javax.swing.JButton();
        btnEsc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtRoleID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        InputFunctionDialog = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtFunctionID = new javax.swing.JTextField();
        txtFunctionName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        btnAddFunction = new javax.swing.JButton();
        btnEditFunction = new javax.swing.JButton();
        btnEsc1 = new javax.swing.JButton();
        InputPermissionDetail = new javax.swing.JDialog();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        comboboxRole = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        comboboxFunction = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        comboboxAction = new javax.swing.JComboBox<>();
        jPanel15 = new javax.swing.JPanel();
        btnAddPermissionDetail = new javax.swing.JButton();
        btnEditPermissionDetail = new javax.swing.JButton();
        btnEsc2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtPermissionDetailID = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        rolePanel = new javax.swing.JPanel();
        actionPanel = new javax.swing.JPanel();
        btnShowRoleDialog = new javax.swing.JButton();
        btnShowEditRoleDialog = new javax.swing.JButton();
        btnDeleteRole = new javax.swing.JButton();
        btnExportRole = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        roleList = new javax.swing.JTable();
        functionPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnShowAddFunctionDialog = new javax.swing.JButton();
        btnShowEditFunctionDialog = new javax.swing.JButton();
        btnDeleteFunction = new javax.swing.JButton();
        btnExportFunction = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        functionList = new javax.swing.JTable();
        permissionDetailPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        showPermissionDetailDialog = new javax.swing.JButton();
        editPermissionDetailDialog = new javax.swing.JButton();
        btnDeletePermissionDetail = new javax.swing.JButton();
        btnExportPermission = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        permissionDetailList = new javax.swing.JTable();

        InputRoleDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        InputRoleDialog.setLocationByPlatform(true);
        InputRoleDialog.setMinimumSize(new java.awt.Dimension(397, 238));
        InputRoleDialog.setModal(true);
        InputRoleDialog.setUndecorated(true);

        jPanel5.setBackground(new java.awt.Color(209, 15, 209));

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nhóm Quyền");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(144, 144, 144))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        btnAddRole.setBackground(new java.awt.Color(209, 15, 209));
        btnAddRole.setForeground(new java.awt.Color(255, 255, 255));
        btnAddRole.setText("Thêm");
        btnAddRole.setPreferredSize(new java.awt.Dimension(100, 35));
        btnAddRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoleActionPerformed(evt);
            }
        });
        jPanel6.add(btnAddRole);

        btnEditRole.setBackground(new java.awt.Color(255, 153, 51));
        btnEditRole.setForeground(new java.awt.Color(255, 255, 255));
        btnEditRole.setText("Sửa");
        btnEditRole.setPreferredSize(new java.awt.Dimension(100, 35));
        btnEditRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditRoleActionPerformed(evt);
            }
        });
        jPanel6.add(btnEditRole);

        btnEsc.setBackground(new java.awt.Color(255, 0, 0));
        btnEsc.setForeground(new java.awt.Color(255, 255, 255));
        btnEsc.setText("Thoát");
        btnEsc.setPreferredSize(new java.awt.Dimension(100, 35));
        btnEsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscActionPerformed(evt);
            }
        });
        jPanel6.add(btnEsc);

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(209, 15, 209));
        jLabel2.setText("Mã nhóm quyền");

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(209, 15, 209));
        jLabel3.setText("Tên nhóm quyền");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRoleID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRoleName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRoleID, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRoleName, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout InputRoleDialogLayout = new javax.swing.GroupLayout(InputRoleDialog.getContentPane());
        InputRoleDialog.getContentPane().setLayout(InputRoleDialogLayout);
        InputRoleDialogLayout.setHorizontalGroup(
            InputRoleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        InputRoleDialogLayout.setVerticalGroup(
            InputRoleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputRoleDialogLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        InputFunctionDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        InputFunctionDialog.setLocationByPlatform(true);
        InputFunctionDialog.setMinimumSize(new java.awt.Dimension(400, 270));
        InputFunctionDialog.setModal(true);
        InputFunctionDialog.setUndecorated(true);

        jPanel9.setBackground(new java.awt.Color(209, 15, 209));
        jPanel9.setPreferredSize(new java.awt.Dimension(262, 70));

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Chức Năng");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(209, 15, 209));
        jLabel5.setText("Mã chức năng");

        jLabel6.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(209, 15, 209));
        jLabel6.setText("Tên chức năng");

        jPanel11.setForeground(new java.awt.Color(255, 255, 255));

        btnAddFunction.setBackground(new java.awt.Color(209, 15, 209));
        btnAddFunction.setForeground(new java.awt.Color(255, 255, 255));
        btnAddFunction.setText("Thêm");
        btnAddFunction.setPreferredSize(new java.awt.Dimension(100, 35));
        btnAddFunction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFunctionActionPerformed(evt);
            }
        });
        jPanel11.add(btnAddFunction);

        btnEditFunction.setBackground(new java.awt.Color(255, 153, 51));
        btnEditFunction.setForeground(new java.awt.Color(255, 255, 255));
        btnEditFunction.setText("Sửa");
        btnEditFunction.setPreferredSize(new java.awt.Dimension(100, 35));
        btnEditFunction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditFunctionActionPerformed(evt);
            }
        });
        jPanel11.add(btnEditFunction);

        btnEsc1.setBackground(new java.awt.Color(255, 0, 0));
        btnEsc1.setForeground(new java.awt.Color(255, 255, 255));
        btnEsc1.setText("Thoát");
        btnEsc1.setPreferredSize(new java.awt.Dimension(100, 35));
        btnEsc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsc1ActionPerformed(evt);
            }
        });
        jPanel11.add(btnEsc1);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtFunctionName, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtFunctionID, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFunctionID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFunctionName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout InputFunctionDialogLayout = new javax.swing.GroupLayout(InputFunctionDialog.getContentPane());
        InputFunctionDialog.getContentPane().setLayout(InputFunctionDialogLayout);
        InputFunctionDialogLayout.setHorizontalGroup(
            InputFunctionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        InputFunctionDialogLayout.setVerticalGroup(
            InputFunctionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputFunctionDialogLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        InputPermissionDetail.setMinimumSize(new java.awt.Dimension(275, 455));
        InputPermissionDetail.setModal(true);
        InputPermissionDetail.setUndecorated(true);

        jPanel13.setBackground(new java.awt.Color(209, 15, 209));

        jLabel7.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Chi Tiết Quyền");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(209, 15, 209));
        jLabel8.setText("Nhóm Quyền");

        jLabel9.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(209, 15, 209));
        jLabel9.setText("Chức năng");

        jLabel10.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(209, 15, 209));
        jLabel10.setText("Hành động");

        comboboxAction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xem", "Sửa", "Xóa", "Thêm" }));

        jPanel15.setForeground(new java.awt.Color(255, 255, 255));

        btnAddPermissionDetail.setBackground(new java.awt.Color(209, 15, 209));
        btnAddPermissionDetail.setForeground(new java.awt.Color(255, 255, 255));
        btnAddPermissionDetail.setText("Thêm");
        btnAddPermissionDetail.setPreferredSize(new java.awt.Dimension(100, 35));
        btnAddPermissionDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPermissionDetailActionPerformed(evt);
            }
        });
        jPanel15.add(btnAddPermissionDetail);

        btnEditPermissionDetail.setBackground(new java.awt.Color(255, 153, 51));
        btnEditPermissionDetail.setForeground(new java.awt.Color(255, 255, 255));
        btnEditPermissionDetail.setText("Sửa");
        btnEditPermissionDetail.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel15.add(btnEditPermissionDetail);

        btnEsc2.setBackground(new java.awt.Color(255, 0, 0));
        btnEsc2.setForeground(new java.awt.Color(255, 255, 255));
        btnEsc2.setText("Thoát");
        btnEsc2.setPreferredSize(new java.awt.Dimension(100, 35));
        btnEsc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsc2ActionPerformed(evt);
            }
        });
        jPanel15.add(btnEsc2);

        jLabel11.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(209, 15, 209));
        jLabel11.setText("Mã chi tiết");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPermissionDetailID)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(comboboxFunction, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addComponent(comboboxRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboboxAction, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPermissionDetailID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboboxRole, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboboxFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboboxAction, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout InputPermissionDetailLayout = new javax.swing.GroupLayout(InputPermissionDetail.getContentPane());
        InputPermissionDetail.getContentPane().setLayout(InputPermissionDetailLayout);
        InputPermissionDetailLayout.setHorizontalGroup(
            InputPermissionDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        InputPermissionDetailLayout.setVerticalGroup(
            InputPermissionDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPermissionDetailLayout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setPreferredSize(new java.awt.Dimension(1050, 600));

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1050, 600));

        actionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Thao tác"));

        btnShowRoleDialog.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        btnShowRoleDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Add.png"))); // NOI18N
        btnShowRoleDialog.setHideActionText(true);
        btnShowRoleDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowRoleDialogActionPerformed(evt);
            }
        });

        btnShowEditRoleDialog.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        btnShowEditRoleDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Edit.png"))); // NOI18N
        btnShowEditRoleDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowEditRoleDialogActionPerformed(evt);
            }
        });

        btnDeleteRole.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        btnDeleteRole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Remove.png"))); // NOI18N
        btnDeleteRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRoleActionPerformed(evt);
            }
        });

        btnExportRole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/XLS.png"))); // NOI18N
        btnExportRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportRoleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionPanelLayout = new javax.swing.GroupLayout(actionPanel);
        actionPanel.setLayout(actionPanelLayout);
        actionPanelLayout.setHorizontalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnShowRoleDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnShowEditRoleDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteRole, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExportRole, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        actionPanelLayout.setVerticalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShowEditRoleDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteRole, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowRoleDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExportRole, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách nhóm quyền"));

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        roleList.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        roleList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã nhóm quyền", "Tên nhóm quyền"
            }
        ));
        roleList.setRowHeight(30);
        roleList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roleListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(roleList);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout rolePanelLayout = new javax.swing.GroupLayout(rolePanel);
        rolePanel.setLayout(rolePanelLayout);
        rolePanelLayout.setHorizontalGroup(
            rolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rolePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(rolePanelLayout.createSequentialGroup()
                        .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        rolePanelLayout.setVerticalGroup(
            rolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rolePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Nhóm quyền", rolePanel);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thao tác"));

        btnShowAddFunctionDialog.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        btnShowAddFunctionDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Add.png"))); // NOI18N
        btnShowAddFunctionDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAddFunctionDialogActionPerformed(evt);
            }
        });

        btnShowEditFunctionDialog.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        btnShowEditFunctionDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Edit.png"))); // NOI18N
        btnShowEditFunctionDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowEditFunctionDialogActionPerformed(evt);
            }
        });

        btnDeleteFunction.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        btnDeleteFunction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Remove.png"))); // NOI18N
        btnDeleteFunction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFunctionActionPerformed(evt);
            }
        });

        btnExportFunction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/XLS.png"))); // NOI18N
        btnExportFunction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportFunctionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnShowAddFunctionDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnShowEditFunctionDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExportFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShowAddFunctionDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnDeleteFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnShowEditFunctionDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnExportFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách chức năng"));

        functionList.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        functionList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                " Mã chức năng", "Tên chức năng"
            }
        ));
        functionList.setRowHeight(30);
        functionList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                functionListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(functionList);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout functionPanelLayout = new javax.swing.GroupLayout(functionPanel);
        functionPanel.setLayout(functionPanelLayout);
        functionPanelLayout.setHorizontalGroup(
            functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(functionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(functionPanelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        functionPanelLayout.setVerticalGroup(
            functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(functionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Chức năng", functionPanel);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Thao tác"));
        jPanel7.setPreferredSize(new java.awt.Dimension(394, 89));

        showPermissionDetailDialog.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        showPermissionDetailDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Add.png"))); // NOI18N
        showPermissionDetailDialog.setPreferredSize(new java.awt.Dimension(60, 60));
        showPermissionDetailDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPermissionDetailDialogActionPerformed(evt);
            }
        });

        editPermissionDetailDialog.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        editPermissionDetailDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Edit.png"))); // NOI18N
        editPermissionDetailDialog.setPreferredSize(new java.awt.Dimension(60, 60));
        editPermissionDetailDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPermissionDetailDialogActionPerformed(evt);
            }
        });

        btnDeletePermissionDetail.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        btnDeletePermissionDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Remove.png"))); // NOI18N
        btnDeletePermissionDetail.setPreferredSize(new java.awt.Dimension(60, 60));
        btnDeletePermissionDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePermissionDetailActionPerformed(evt);
            }
        });

        btnExportPermission.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/XLS.png"))); // NOI18N
        btnExportPermission.setPreferredSize(new java.awt.Dimension(60, 60));
        btnExportPermission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportPermissionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showPermissionDetailDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editPermissionDetailDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeletePermissionDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExportPermission, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showPermissionDetailDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnDeletePermissionDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editPermissionDetailDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExportPermission, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách chi tiết quyền"));

        permissionDetailList.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        permissionDetailList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã chi tiết quyền", "Nhóm quyền", "Chức năng", "Hành động"
            }
        ));
        permissionDetailList.setRowHeight(30);
        permissionDetailList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                permissionDetailListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(permissionDetailList);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout permissionDetailPanelLayout = new javax.swing.GroupLayout(permissionDetailPanel);
        permissionDetailPanel.setLayout(permissionDetailPanelLayout);
        permissionDetailPanelLayout.setHorizontalGroup(
            permissionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permissionDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(permissionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(permissionDetailPanelLayout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        permissionDetailPanelLayout.setVerticalGroup(
            permissionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permissionDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Chi tiết quyền", permissionDetailPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // load dữ liệu nhóm quyền lên bảng
    public void loadDataRole() {
        DefaultTableModel model = (DefaultTableModel) roleList.getModel();
        model.setRowCount(0); // xóa table 
        for (Role role : roleBUS.getAllRole()) {
            Object dataRow[] = new Object[2];
            dataRow[0] = role.getRoleID();
            dataRow[1] = role.getRoleName();
            model.addRow(dataRow);
        }
    }

    // load dữ liệu chức năng
    public void loadDataFunction() {
        DefaultTableModel model = (DefaultTableModel) functionList.getModel();
        model.setRowCount(0); // xóa table 
        for (Function function : functionBUS.getAllFunction()) {
            Object dataRow[] = new Object[2];
            dataRow[0] = function.getFunctionID();
            dataRow[1] = function.getFunctionName();
            model.addRow(dataRow);
        }
    }

    // load dữ liệu chi tiết quyền
    public void loadDataPermissionDetail() {
        DefaultTableModel model = (DefaultTableModel) permissionDetailList.getModel();
        model.setRowCount(0); // xóa table 
        for (PermissionDetail psm : permissionDetailBUS.getAllPermissionDetail()) {
            Object dataRow[] = new Object[4];
            dataRow[0] = psm.getPermissionDetailID();
            String roleID = psm.getRoleID();
            dataRow[1] = roleBUS.getRoleByID(roleID).getRoleName();
            String functionID = psm.getFunctionID();
            dataRow[2] = functionBUS.getFunctionByID(functionID).getFunctionName();
            dataRow[3] = psm.getAction();
            model.addRow(dataRow);
        }
    }

    // get role model 
    public Role getRoleModel() {
        Role role = new Role();
        role.setRoleID(txtRoleID.getText());
        role.setRoleName(txtRoleName.getText());
        role.setStatus(1);
        return role;
    }

    // set role model
    public void setRoleModel(Role role) {
        txtRoleID.setText(role.getRoleID());
        txtRoleName.setText(role.getRoleName());
    }

    // xóa nhóm quyền
    private void btnDeleteRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRoleActionPerformed
        // TODO add your handling code here:
        if (validateRoleForm()) {
            if (roleBUS.deleteRole(txtRoleID.getText())) {
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                loadDataRole();
                loadComboboxRole();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhóm quyền muốn xóa");

        }


    }//GEN-LAST:event_btnDeleteRoleActionPerformed

    // hiển thị form nhập nhóm quyền
    private void btnShowRoleDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowRoleDialogActionPerformed
        // TODO add your handling code here:
        InputRoleDialog.setLocationRelativeTo(null);
        loadComboboxRole();
        loadComboboxFunction();
        loadDataRole();
        loadDataFunction();
        loadDataPermissionDetail();
        resetRoleForm();
        btnAddRole.setVisible(true);
        btnEditRole.setVisible(false);
        InputRoleDialog.setVisible(true);

    }//GEN-LAST:event_btnShowRoleDialogActionPerformed

    // hiển thị form sửa nhóm quyền
    private void btnShowEditRoleDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowEditRoleDialogActionPerformed
        // TODO add your handling code here:
        if (txtRoleID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhóm quyền muốn sửa");
        } else {

            InputRoleDialog.setLocationRelativeTo(null);
            btnAddRole.setVisible(false);
            btnEditRole.setVisible(true);
            loadDataRole();
            loadDataFunction();
            loadComboboxRole();
            loadComboboxFunction();
            loadDataPermissionDetail();
            InputRoleDialog.setVisible(true);
        }
    }//GEN-LAST:event_btnShowEditRoleDialogActionPerformed

    private void btnEscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscActionPerformed
        // TODO add your handling code here:
        InputRoleDialog.dispose();
        resetRoleForm();
    }//GEN-LAST:event_btnEscActionPerformed

    // kiểm tra xem các trường dữ liệu dialog nhóm quyền có được nhập đủ không
    public boolean validateRoleForm() {
        if (txtRoleID.getText().isEmpty() || txtRoleName.getText().isEmpty()) {
            return false;
        }
        return true;
    }

    // reset trường dữ liệu nhóm quyền
    public void resetRoleForm() {
        txtRoleID.setText("");
        txtRoleName.setText("");
    }

    // xử lý sự kiện khi ấn nút thêm trong dialog nhóm quyền
    private void btnAddRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoleActionPerformed
        // TODO add your handling code here:
        if (validateRoleForm()) {
            Role role = getRoleModel();
            if (roleBUS.addRole(role)) {
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                resetRoleForm();
                InputRoleDialog.setVisible(false);
                loadDataRole();
                loadComboboxRole();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
        }

    }//GEN-LAST:event_btnAddRoleActionPerformed

    // lấy  nhóm quyền khi ấn vào 1 hàng trong bảng
    private void roleListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roleListMouseClicked
        // TODO add your handling code here:
        int row = roleList.rowAtPoint(evt.getPoint());
        String roleID = roleList.getValueAt(row, 0).toString();
        Role role = roleBUS.getRoleByID(roleID);
        setRoleModel(role);
    }//GEN-LAST:event_roleListMouseClicked

    // set model chức năng
    public void setFunctionModel(Function function) {
        txtFunctionID.setText(function.getFunctionID());
        txtFunctionName.setText(function.getFunctionName());
    }

    // get model chức năng
    public Function getFunctionModel() {
        Function function = new Function();
        function.setFunctionID(txtFunctionID.getText());
        function.setFunctionName(txtFunctionName.getText());
        function.setStatus(1);
        return function;
    }

    // hiển thị form nhập chức năng
    private void btnShowAddFunctionDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAddFunctionDialogActionPerformed
        InputFunctionDialog.setLocationRelativeTo(null);
        resetFunctionForm();
        btnAddFunction.setVisible(true);
        btnEditFunction.setVisible(false);
        InputFunctionDialog.setVisible(true);
    }//GEN-LAST:event_btnShowAddFunctionDialogActionPerformed

    // kiểm tra nhập form chức năng
    public boolean validateFormFunction() {
        if (txtFunctionID.getText().isEmpty() || txtFunctionName.getText().isEmpty()) {
            return false;
        }
        return true;
    }

    // thêm chức năng
    private void btnAddFunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFunctionActionPerformed
        // TODO add your handling code here:
        if (validateFormFunction()) {
            Function function = getFunctionModel();
            if (functionBUS.addFunction(function)) {
                JOptionPane.showMessageDialog(this, "Thêm chức năng thành công");
                InputFunctionDialog.setVisible(false);
                loadDataFunction();
                loadComboboxFunction();

            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
        }
    }//GEN-LAST:event_btnAddFunctionActionPerformed

    // hàm reset trường dữ liệu form chức năng
    public void resetFunctionForm() {
        txtFunctionID.setText("");
        txtFunctionName.setText("");
    }

    // xử lý ấn nút thoát form chức năng
    private void btnEsc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsc1ActionPerformed

        InputFunctionDialog.setVisible(false);
        resetFunctionForm();
    }//GEN-LAST:event_btnEsc1ActionPerformed

    // hiển thị form sửa chức năng
    private void btnShowEditFunctionDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowEditFunctionDialogActionPerformed
        // TODO add your handling code here:
        if (validateFormFunction()) {
            InputFunctionDialog.setLocationRelativeTo(null);
            btnAddFunction.setVisible(false);
            btnEditFunction.setVisible(true);
            InputFunctionDialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn chức năng muốn sửa");
        }

    }//GEN-LAST:event_btnShowEditFunctionDialogActionPerformed

    private void functionListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_functionListMouseClicked
        // TODO add your handling code here:
        int row = functionList.rowAtPoint(evt.getPoint());
        String functionID = functionList.getValueAt(row, 0).toString();
        Function function = functionBUS.getFunctionByID(functionID);
        setFunctionModel(function);

    }//GEN-LAST:event_functionListMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    // Ấn nút sửa chức năng trên form
    private void btnEditFunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditFunctionActionPerformed
        // TODO add your handling code here:
        Function function = getFunctionModel();
        if (validateFormFunction()) {
            if (functionBUS.editFunction(function)) {
                JOptionPane.showMessageDialog(this, "Sửa chức năng thành công");
                InputFunctionDialog.dispose();
                loadDataFunction();
                loadDataFunction();
            } else {
                JOptionPane.showMessageDialog(this, "Sửa thất bại");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
        }


    }//GEN-LAST:event_btnEditFunctionActionPerformed

    // Xóa chức năng
    private void btnDeleteFunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFunctionActionPerformed
        // TODO add your handling code here:
        Function function = getFunctionModel();
        if (functionBUS.deleteFunction(function.getFunctionID())) {
            JOptionPane.showMessageDialog(this, "Xóa chức năng thành công");
            loadDataFunction();
            loadComboboxFunction();
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
    }//GEN-LAST:event_btnDeleteFunctionActionPerformed

    public void resetPermissionDetail() {

    }

    public void loadComboboxRole() {
        DefaultComboBoxModel roleModel = new DefaultComboBoxModel();
        for (Role role : roleBUS.getAllRole()) {
            roleModel.addElement(role.getRoleName());
        }
        comboboxRole.setModel(roleModel);
    }

    public void loadComboboxFunction() {
        DefaultComboBoxModel functionModel = new DefaultComboBoxModel();
        for (Function function : functionBUS.getAllFunction()) {
            functionModel.addElement(function.getFunctionName());
        }
        comboboxFunction.setModel(functionModel);
    }
    private void showPermissionDetailDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPermissionDetailDialogActionPerformed
        // TODO add your handling code here:
        InputPermissionDetail.setLocationRelativeTo(null);
        loadComboboxRole();
        loadComboboxFunction();
        btnAddPermissionDetail.setVisible(true);
        btnEditPermissionDetail.setVisible(false);
        InputPermissionDetail.setVisible(true);
    }//GEN-LAST:event_showPermissionDetailDialogActionPerformed

    public PermissionDetail getPermissionDetailModel() {
        PermissionDetail psm = new PermissionDetail();
        psm.setPermissionDetailID(txtPermissionDetailID.getText());
        String roleID = roleBUS.getRoleByName(comboboxRole.getSelectedItem().toString()).getRoleID();
        String functionID = functionBUS.getFunctionByName(comboboxFunction.getSelectedItem().toString()).getFunctionID();
        psm.setRoleID(roleID);
        psm.setFunctionID(functionID);
        psm.setAction(comboboxAction.getSelectedItem().toString());
        return psm;
    }

    public void setPermissionDetailModel(PermissionDetail psm) {
        txtPermissionDetailID.setText(psm.getPermissionDetailID());
        String roleName = roleBUS.getRoleByID(psm.getRoleID()).getRoleName();
        String functionName = functionBUS.getFunctionByID(psm.getFunctionID()).getFunctionName();
        System.out.println(roleName + " " + functionName);
        comboboxRole.setSelectedItem(roleName);
        comboboxFunction.setSelectedItem(functionName);
        comboboxAction.setSelectedItem(psm.getAction());

    }

    public boolean validateFormPermissionDetail() {
        if (txtPermissionDetailID.getText().isEmpty()) {
            return false;
        }
        return true;
    }
    private void btnAddPermissionDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPermissionDetailActionPerformed
        // TODO add your handling code here:
        if (validateFormPermissionDetail()) {
            PermissionDetail psm = getPermissionDetailModel();
            if (permissionDetailBUS.addPermissionDetail(psm)) {
                JOptionPane.showMessageDialog(this, "Thêm chi tiết quyền thành công");
                loadDataPermissionDetail();
            } else {
                JOptionPane.showMessageDialog(this, "Thất bại");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
        }

    }//GEN-LAST:event_btnAddPermissionDetailActionPerformed

    private void btnEsc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsc2ActionPerformed
        // TODO add your handling code here:
        InputPermissionDetail.setVisible(false);
    }//GEN-LAST:event_btnEsc2ActionPerformed

    private void btnEditRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditRoleActionPerformed
        // TODO add your handling code here:
        Role role = getRoleModel();
        if (roleBUS.editRole(role)) {
            JOptionPane.showMessageDialog(this, "Sửa nhóm quyền thành công");
            InputFunctionDialog.setVisible(false);
            loadDataRole();
            loadComboboxRole();
        } else {
            JOptionPane.showMessageDialog(this, "Sửa thất bại");
        }
    }//GEN-LAST:event_btnEditRoleActionPerformed

    // Click chọn 1 dòng trên bảng chi tiết quyền
    private void permissionDetailListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_permissionDetailListMouseClicked
        // TODO add your handling code here:
        int row = permissionDetailList.rowAtPoint(evt.getPoint());
        String permissionDetailID = permissionDetailList.getValueAt(row, 0).toString();
        PermissionDetail psm = permissionDetailBUS.getPermissionDetailByID(permissionDetailID);
        setPermissionDetailModel(psm);

    }//GEN-LAST:event_permissionDetailListMouseClicked

    // Xóa chi tiết quyền
    private void btnDeletePermissionDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePermissionDetailActionPerformed
        // TODO add your handling code here:
        if (validateFormPermissionDetail()) {
            PermissionDetail psm = getPermissionDetailModel();
            if (permissionDetailBUS.deletePermissionDetail(psm.getPermissionDetailID())) {
                JOptionPane.showMessageDialog(this, "Xóa chi tiết quyền thành công");
                InputPermissionDetail.setVisible(false);
                loadDataPermissionDetail();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn chi tiết quyền cần xóa");
        }

    }//GEN-LAST:event_btnDeletePermissionDetailActionPerformed

    private void editPermissionDetailDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPermissionDetailDialogActionPerformed
        // TODO add your handling code here:
        InputPermissionDetail.setLocationRelativeTo(null);
        btnAddPermissionDetail.setVisible(false);
        btnEditPermissionDetail.setVisible(true);
        InputPermissionDetail.setVisible(true);
    }//GEN-LAST:event_editPermissionDetailDialogActionPerformed

    private void btnExportRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportRoleActionPerformed
        try {
            JFileChooser choose = new JFileChooser();
            choose.showOpenDialog(JOptionPane.getRootFrame());
            File save = choose.getSelectedFile();
            if (save != null) {
                save = new File(save.toString() + ".xlsx");
                Workbook wb = new XSSFWorkbook();
                Sheet sheet = (Sheet) wb.createSheet("Nhóm quyền");
                Row rowcol = sheet.createRow(0);
                for (int i = 0; i < roleList.getColumnCount(); i++) {
                    Cell cell = rowcol.createCell(i);
                    cell.setCellValue(roleList.getColumnName(i));
                }
                for (int i = 0; i < roleList.getRowCount(); i++) {
                    Row row = sheet.createRow(i + 1);
                    for (int j = 0; j < roleList.getColumnCount(); j++) {
                        Cell cell = row.createCell(j);
                        if (roleList.getValueAt(i, j) != null) {
                            cell.setCellValue(roleList.getValueAt(i, j).toString());
                        }
                    }
                }
                FileOutputStream out = new FileOutputStream(new File(save.toString()));
                wb.write(out);
                wb.close();
                out.close();
                openFile(save.toString());
            } else {
                JOptionPane.showMessageDialog(null, "Error al genera");
            }
        } catch (Exception u) {
            u.printStackTrace();
        }
    }//GEN-LAST:event_btnExportRoleActionPerformed

    // Hàm mở file
    public void openFile(String file) {
        try {
            File path = new File(file);
            Desktop.getDesktop().open(path);
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    private void btnExportFunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportFunctionActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser choose = new JFileChooser();
            choose.showOpenDialog(JOptionPane.getRootFrame());
            File save = choose.getSelectedFile();
            if (save != null) {
                save = new File(save.toString() + ".xlsx");
                Workbook wb = new XSSFWorkbook();
                Sheet sheet = (Sheet) wb.createSheet("Chức năng");
                Row rowcol = sheet.createRow(0);
                for (int i = 0; i < functionList.getColumnCount(); i++) {
                    Cell cell = rowcol.createCell(i);
                    cell.setCellValue(functionList.getColumnName(i));
                }
                for (int i = 0; i < functionList.getRowCount(); i++) {
                    Row row = sheet.createRow(i + 1);
                    for (int j = 0; j < functionList.getColumnCount(); j++) {
                        Cell cell = row.createCell(j);
                        if (functionList.getValueAt(i, j) != null) {
                            cell.setCellValue(functionList.getValueAt(i, j).toString());
                        }
                    }
                }
                FileOutputStream out = new FileOutputStream(new File(save.toString()));
                wb.write(out);
                wb.close();
                out.close();
                openFile(save.toString());
            } else {
                JOptionPane.showMessageDialog(null, "Error al genera");
            }
        } catch (Exception u) {
            u.printStackTrace();
        }
    }//GEN-LAST:event_btnExportFunctionActionPerformed

    private void btnExportPermissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportPermissionActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try {
            JFileChooser choose = new JFileChooser();
            choose.showOpenDialog(JOptionPane.getRootFrame());
            File save = choose.getSelectedFile();
            if (save != null) {
                save = new File(save.toString() + ".xlsx");
                Workbook wb = new XSSFWorkbook();
                Sheet sheet = (Sheet) wb.createSheet("Chi tiết quyền");
                Row rowcol = sheet.createRow(0);
                for (int i = 0; i < permissionDetailList.getColumnCount(); i++) {
                    Cell cell = rowcol.createCell(i);
                    cell.setCellValue(permissionDetailList.getColumnName(i));
                }
                for (int i = 0; i < permissionDetailList.getRowCount(); i++) {
                    Row row = sheet.createRow(i + 1);
                    for (int j = 0; j < permissionDetailList.getColumnCount(); j++) {
                        Cell cell = row.createCell(j);
                        if (permissionDetailList.getValueAt(i, j) != null) {
                            cell.setCellValue(permissionDetailList.getValueAt(i, j).toString());
                        }
                    }
                }
                FileOutputStream out = new FileOutputStream(new File(save.toString()));
                wb.write(out);
                wb.close();
                out.close();
                openFile(save.toString());
            } else {
                JOptionPane.showMessageDialog(null, "Error al genera");
            }
        } catch (Exception u) {
            u.printStackTrace();
        }
    }//GEN-LAST:event_btnExportPermissionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog InputFunctionDialog;
    private javax.swing.JDialog InputPermissionDetail;
    private javax.swing.JDialog InputRoleDialog;
    private javax.swing.JPanel actionPanel;
    private javax.swing.JButton btnAddFunction;
    private javax.swing.JButton btnAddPermissionDetail;
    private javax.swing.JButton btnAddRole;
    private javax.swing.JButton btnDeleteFunction;
    private javax.swing.JButton btnDeletePermissionDetail;
    private javax.swing.JButton btnDeleteRole;
    private javax.swing.JButton btnEditFunction;
    private javax.swing.JButton btnEditPermissionDetail;
    private javax.swing.JButton btnEditRole;
    private javax.swing.JButton btnEsc;
    private javax.swing.JButton btnEsc1;
    private javax.swing.JButton btnEsc2;
    private javax.swing.JButton btnExportFunction;
    private javax.swing.JButton btnExportPermission;
    private javax.swing.JButton btnExportRole;
    private javax.swing.JButton btnShowAddFunctionDialog;
    private javax.swing.JButton btnShowEditFunctionDialog;
    private javax.swing.JButton btnShowEditRoleDialog;
    private javax.swing.JButton btnShowRoleDialog;
    private javax.swing.JComboBox<String> comboboxAction;
    private javax.swing.JComboBox<String> comboboxFunction;
    private javax.swing.JComboBox<String> comboboxRole;
    private javax.swing.JButton editPermissionDetailDialog;
    private javax.swing.JTable functionList;
    private javax.swing.JPanel functionPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable permissionDetailList;
    private javax.swing.JPanel permissionDetailPanel;
    private javax.swing.JTable roleList;
    private javax.swing.JPanel rolePanel;
    private javax.swing.JButton showPermissionDetailDialog;
    private javax.swing.JTextField txtFunctionID;
    private javax.swing.JTextField txtFunctionName;
    private javax.swing.JTextField txtPermissionDetailID;
    private javax.swing.JTextField txtRoleID;
    private javax.swing.JTextField txtRoleName;
    // End of variables declaration//GEN-END:variables
}
